name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - mlflow=2.3.2
  - ipython=8.13.2
  - notebook=6.5.4
  - jupyterlab=4.0.0
  - cookiecutter=2.1.1
  - hydra-core=1.3.2
  - matplotlib=3.7.1
  - pandas=2.0.1
  - git=4.0.10
  - pip=23.1.2
  - pip:
      - wandb==0.15.3
